"""add embedding column to tickets

Revision ID: aeae667bd3f3
Revises: 475547a1ecb9
Create Date: 2026-08-15 23:26:47.276580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'aeae667bd3f3'
down_revision: Union[str, None] = '475547a1ecb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('embedding', Vector(768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'embedding')
    # ### end Alembic commands ###
